#!/usr/bin/env bash
# This script displays the contents of /etc/passwd, but only the username, user ID and Home directory path for the user
while IFS= read -r line; do
    echo "$line" | cut -d: -f1,3,6
done < /etc/passwd
