#!/usr/bin/env bash
# This script displays the contents of /etc/passwd in the format of: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place  #+ is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
while IFS=':' read -r username password userid groupID description homedir shell; do
    echo "The user $username is part of the $groupID gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $description"
done < /etc/passwd
