#!/usr/bin/env bash
# Displays 4 and then bad luck from China for the 4th loop iteration, displays 9, bad luck from Japan for the 9th iteration,displays 17, bad luck from Italy for the 17th iteration
i=1
while [ $i -le 20 ]
do
	case "$i" in
	     4)echo -e "$i\nbad luck from China" ;;
             9)echo -e "$i\nbad luck from Japan" ;;
	    17)echo -e "$i\nbad luck from Italy" ;;
	     *)echo "$i"
        esac
	((i++))	
done

